"""Tests for generateCatalogInfo.py."""

from generateCatalogInfo import (
    DEFAULT_OVERLAY_SLUG,
    RHDH_PLUGINS_COMPONENT_BY_WORKSPACE,
    ROOT_COMPONENT_NAME,
    build_root_entity,
    build_workspace_entity,
    check_files,
    dump_entity,
    is_rhdh_plugins_source,
    overlay_entity_name,
    overlay_tree_url,
    planned_files,
    rhdh_plugins_depends_on,
    source_tree_url,
    write_files,
)


RHDH_PLUGINS_SOURCE = {
    "repo": "https://github.com/redhat-developer/rhdh-plugins",
    "repo-ref": "97a6e3a7c468a7624b62f957fc7c077127bf51c6",
    "repo-flat": False,
    "repo-backstage-version": "1.52.0",
}

COMMUNITY_SOURCE = {
    "repo": "https://github.com/backstage/community-plugins",
    "repo-ref": "0e830be044ca334c5304b541e4757b621eb1e6db",
    "repo-flat": False,
    "repo-backstage-version": "1.52.0",
}

FLAT_SOURCE = {
    "repo": "https://github.com/backstage/backstage",
    "repo-ref": "v1.52.0",
    "repo-flat": True,
    "repo-backstage-version": "1.52.0",
}


def test_overlay_entity_name():
    assert overlay_entity_name("bulk-import") == "overlay-bulk-import"


def test_is_rhdh_plugins_source():
    assert is_rhdh_plugins_source(RHDH_PLUGINS_SOURCE["repo"])
    assert not is_rhdh_plugins_source(COMMUNITY_SOURCE["repo"])


def test_source_tree_url_nested():
    assert source_tree_url(RHDH_PLUGINS_SOURCE, "bulk-import") == (
        "https://github.com/redhat-developer/rhdh-plugins/tree/"
        "97a6e3a7c468a7624b62f957fc7c077127bf51c6/workspaces/bulk-import"
    )


def test_source_tree_url_flat():
    assert source_tree_url(FLAT_SOURCE, "backstage") == (
        "https://github.com/backstage/backstage/tree/v1.52.0"
    )


def test_overlay_tree_url():
    assert overlay_tree_url(DEFAULT_OVERLAY_SLUG, "bulk-import") == (
        "https://github.com/rhdh-parasol/rhdh-plugin-export-overlays/tree/"
        "main/workspaces/bulk-import"
    )


def test_depends_on_only_for_known_rhdh_plugins_workspaces():
    assert rhdh_plugins_depends_on("bulk-import") == (
        "red-hat-developer-hub-bulk-import"
    )
    assert rhdh_plugins_depends_on("konflux") is None
    assert rhdh_plugins_depends_on("github") is None
    assert "konflux" not in RHDH_PLUGINS_COMPONENT_BY_WORKSPACE


def test_workspace_entity_rhdh_plugins_has_depends_on():
    entity = build_workspace_entity(
        "bulk-import",
        RHDH_PLUGINS_SOURCE,
        ["plugins/bulk-import", "plugins/bulk-import-backend"],
        DEFAULT_OVERLAY_SLUG,
    )
    assert entity["metadata"]["name"] == "overlay-bulk-import"
    assert entity["spec"]["type"] == "rhdh-overlay-workspace"
    assert entity["spec"]["subcomponentOf"] == ROOT_COMPONENT_NAME
    assert entity["spec"]["dependsOn"] == [
        "component:default/red-hat-developer-hub-bulk-import"
    ]
    assert (
        entity["metadata"]["annotations"]["github.com/project-slug"]
        == DEFAULT_OVERLAY_SLUG
    )


def test_workspace_entity_community_has_no_depends_on():
    entity = build_workspace_entity(
        "github",
        COMMUNITY_SOURCE,
        ["plugins/github-actions"],
        DEFAULT_OVERLAY_SLUG,
    )
    assert "dependsOn" not in entity["spec"]
    assert entity["metadata"]["name"] == "overlay-github"


def test_workspace_entity_unmapped_rhdh_plugins_has_no_depends_on():
    entity = build_workspace_entity(
        "konflux",
        RHDH_PLUGINS_SOURCE,
        ["plugins/konflux", "plugins/konflux-backend"],
        DEFAULT_OVERLAY_SLUG,
    )
    assert "dependsOn" not in entity["spec"]


def test_root_entity():
    entity = build_root_entity(DEFAULT_OVERLAY_SLUG, 65)
    assert entity["metadata"]["name"] == ROOT_COMPONENT_NAME
    assert entity["spec"]["type"] == "repository"
    assert "65 overlay workspaces" in entity["metadata"]["description"]


def test_dump_entity_has_generator_header():
    rendered = dump_entity(build_root_entity(DEFAULT_OVERLAY_SLUG, 1))
    assert rendered.startswith("# Generated by scripts/generateCatalogInfo.py")
    assert "apiVersion: backstage.io/v1alpha1" in rendered


def test_planned_files_and_check(tmp_path):
    ws = tmp_path / "workspaces" / "bulk-import"
    ws.mkdir(parents=True)
    (ws / "source.json").write_text(
        '{"repo":"https://github.com/redhat-developer/rhdh-plugins",'
        '"repo-ref":"abc1234","repo-flat":false}\n',
        encoding="utf-8",
    )
    (ws / "plugins-list.yaml").write_text(
        "plugins/bulk-import:\nplugins/bulk-import-backend:\n",
        encoding="utf-8",
    )

    files = planned_files(tmp_path, DEFAULT_OVERLAY_SLUG)
    paths = [path for path, _ in files]
    assert tmp_path / "catalog-info.yaml" in paths
    assert ws / "catalog-info.yaml" in paths
    assert check_files(files) == 1

    write_files(files, dry_run=False)
    assert check_files(files) == 0

    (ws / "catalog-info.yaml").write_text("stale\n", encoding="utf-8")
    assert check_files(files) == 1
