#!/usr/bin/env python3
#
# Copyright (c) Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
# Generate software-catalog catalog-info.yaml files for this overlay
# repository. These are Backstage kind: Component descriptors consumed by
# GithubEntityProvider (path /workspaces/*/catalog-info.yaml), not the
# Extensions Catalog Plugin/Package entities under metadata/ and
# catalog-entities/extensions/.
#
# Usage:
#   python3 scripts/generateCatalogInfo.py
#   python3 scripts/generateCatalogInfo.py --check

from __future__ import annotations

import argparse
import json
import sys
from collections import defaultdict
from pathlib import Path
from typing import Any

import yaml

from plugin_utils import (
    log_error,
    log_info,
    log_warn,
    read_plugins_list,
    set_debug,
)

GENERATED_HEADER = """\
# Generated by scripts/generateCatalogInfo.py. Do not edit by hand.
# Re-run: python3 scripts/generateCatalogInfo.py
"""

DEFAULT_OVERLAY_SLUG = "rhdh-parasol/rhdh-plugin-export-overlays"
ROOT_COMPONENT_NAME = "rhdh-plugin-export-overlays"
ANNOTATION_OVERLAY_WORKSPACE = "rhdh.io/overlay-workspace"
ANNOTATION_SOURCE_REPOSITORY = "rhdh.io/source-repository"
ANNOTATION_SOURCE_REVISION = "rhdh.io/source-revision"
ANNOTATION_PLUGIN_REFS = "rhdh.io/extensions-plugin-refs"
ANNOTATION_PACKAGE_REFS = "rhdh.io/extensions-package-refs"

# Software-catalog Component metadata.name in rhdh-plugins workspaces/*/catalog-info.yaml.
# Only set spec.dependsOn when the source plugin already has a Component in the
# Parasol software catalog. Overlay workspaces sourced from community-plugins
# (or other repos) are omitted on purpose.
RHDH_PLUGINS_COMPONENT_BY_WORKSPACE: dict[str, str] = {
    "adoption-insights": "adoption-insights",
    "ai-integrations": "ai-integrations",
    "app-defaults": "app-defaults",
    "boost": "boost",
    "bulk-import": "red-hat-developer-hub-bulk-import",
    "cost-management": "cost-management",
    "extensions": "red-hat-developer-hub-extensions",
    "global-header": "red-hat-developer-hub-global-header",
    "homepage": "red-hat-developer-hub-homepage",
    "intelligent-assistant": "developer-intelligent-assistant",
    "mcp-integrations": "mcp-integrations",
    "orchestrator": "red-hat-developer-hub-orchestrator",
    "quickstart": "quickstart",
    "scorecard": "scorecard",
    "theme": "red-hat-developer-hub-theme",
    "translations": "translations",
    "x2a": "red-hat-developer-hub-x2a-frontend",
}


def overlay_entity_name(workspace: str) -> str:
    return f"overlay-{workspace}"


def is_rhdh_plugins_source(repo: str) -> bool:
    return repo.rstrip("/").endswith("/rhdh-plugins")


def source_tree_url(source: dict, workspace: str) -> str:
    repo = source["repo"].rstrip("/")
    ref = source.get("repo-ref") or "main"
    if source.get("repo-flat"):
        return f"{repo}/tree/{ref}"
    return f"{repo}/tree/{ref}/workspaces/{workspace}"


def overlay_tree_url(overlay_slug: str, workspace: str) -> str:
    return f"https://github.com/{overlay_slug}/tree/main/workspaces/{workspace}"


def export_workflow_url(overlay_slug: str) -> str:
    return (
        f"https://github.com/{overlay_slug}/actions/workflows/"
        "publish-workspace-plugins.yaml"
    )


def rhdh_plugins_depends_on(workspace: str) -> str | None:
    return RHDH_PLUGINS_COMPONENT_BY_WORKSPACE.get(workspace)


def load_source_json(workspace_dir: Path) -> dict:
    source_file = workspace_dir / "source.json"
    with source_file.open(encoding="utf-8") as handle:
        return json.load(handle)


def load_yaml(path: Path) -> dict[str, Any] | None:
    """Load one YAML entity, returning None for malformed/non-mapping files."""
    try:
        with path.open(encoding="utf-8") as handle:
            value = yaml.safe_load(handle)
    except (OSError, yaml.YAMLError) as error:
        log_warn(f"Skipping unreadable YAML {path}: {error}")
        return None
    if not isinstance(value, dict):
        log_warn(f"Skipping non-mapping YAML {path}")
        return None
    return value


def canonical_entity_ref(kind: str, namespace: str, name: str) -> str:
    return f"{kind.lower()}:{namespace}/{name}"


def package_name_from_plugin_entry(entry: Any) -> str | None:
    if isinstance(entry, str) and entry:
        return entry
    if isinstance(entry, dict) and isinstance(entry.get("name"), str):
        return entry["name"]
    return None


def normalize_part_of_ref(value: Any) -> tuple[str, str] | None:
    """Return (namespace, name) for the common Package.spec.partOf shapes."""
    if isinstance(value, dict):
        value = value.get("name") or value.get("ref")
    if not isinstance(value, str) or not value.strip():
        return None
    value = value.strip()
    if value.startswith("plugin:"):
        value = value.removeprefix("plugin:")
    if "/" in value:
        namespace, name = value.split("/", 1)
        return namespace or "rhdh", name
    return "rhdh", value


def extension_entities(repo_root: Path) -> dict[str, list[dict[str, Any]]]:
    """Index Extensions Catalog Plugin entities by canonical ref."""
    entities: dict[str, list[dict[str, Any]]] = defaultdict(list)
    plugin_dir = repo_root / "catalog-entities" / "extensions" / "plugins"
    if not plugin_dir.is_dir():
        return entities
    for path in sorted(plugin_dir.glob("*.yaml")):
        entity = load_yaml(path)
        if entity is None or entity.get("kind") != "Plugin":
            continue
        metadata = entity.get("metadata")
        if not isinstance(metadata, dict):
            continue
        namespace = metadata.get("namespace", "default")
        name = metadata.get("name")
        if isinstance(namespace, str) and isinstance(name, str) and name:
            entities[canonical_entity_ref("plugin", namespace, name)].append(entity)
    return entities


def workspace_packages(workspace_dir: Path) -> list[dict[str, Any]]:
    """Return valid Extensions Package entities declared by one workspace."""
    packages: list[dict[str, Any]] = []
    metadata_dir = workspace_dir / "metadata"
    if not metadata_dir.is_dir():
        return packages
    for path in sorted(metadata_dir.glob("*.yaml")):
        entity = load_yaml(path)
        if entity is None or entity.get("kind") != "Package":
            continue
        metadata = entity.get("metadata")
        if not isinstance(metadata, dict):
            continue
        if isinstance(metadata.get("name"), str) and metadata["name"]:
            packages.append(entity)
    return packages


def extension_refs(
    repo_root: Path, workspace_dir: Path
) -> tuple[list[str], list[str]]:
    """Derive verified Plugin and Package refs from existing Extensions YAML."""
    packages = workspace_packages(workspace_dir)
    package_refs: list[str] = []
    packages_by_plugin: dict[str, set[str]] = defaultdict(set)
    for package in packages:
        metadata = package["metadata"]
        namespace = metadata.get("namespace", "default")
        package_name = metadata["name"]
        if not isinstance(namespace, str):
            namespace = "default"
        package_refs.append(canonical_entity_ref("package", namespace, package_name))
        part_of = package.get("spec", {}).get("partOf", [])
        if not isinstance(part_of, list):
            part_of = [part_of]
        for value in part_of:
            normalized = normalize_part_of_ref(value)
            if normalized is None:
                log_warn(
                    f"{workspace_dir.name}: ignoring invalid Package.spec.partOf {value!r}"
                )
                continue
            plugin_ref = canonical_entity_ref("plugin", *normalized)
            packages_by_plugin[plugin_ref].add(package_name)

    plugin_entities = extension_entities(repo_root)
    plugin_refs: list[str] = []
    for plugin_ref, package_names in sorted(packages_by_plugin.items()):
        matches = plugin_entities.get(plugin_ref, [])
        if not matches:
            log_warn(
                f"{workspace_dir.name}: Package metadata references missing {plugin_ref}"
            )
            continue
        if len(matches) != 1:
            log_warn(
                f"{workspace_dir.name}: Package metadata references ambiguous {plugin_ref}"
            )
            continue
        expected = {
            name
            for name in (
                package_name_from_plugin_entry(entry)
                for entry in matches[0].get("spec", {}).get("packages", [])
            )
            if name
        }
        unexpected = package_names - expected
        if unexpected or not expected:
            log_warn(
                f"{workspace_dir.name}: omitting {plugin_ref}; Package names not present "
                f"in Plugin.spec.packages: {', '.join(sorted(unexpected)) or 'none'}"
            )
            continue
        plugin_refs.append(plugin_ref)

    return sorted(set(plugin_refs)), sorted(set(package_refs))


class _IndentDumper(yaml.SafeDumper):
    """Keep list items indented under their parent key."""

    def increase_indent(self, flow=False, indentless=False):
        return super().increase_indent(flow, False)


def dump_entity(entity: dict) -> str:
    body = yaml.dump(
        entity,
        Dumper=_IndentDumper,
        sort_keys=False,
        default_flow_style=False,
        allow_unicode=True,
        width=120,
    )
    return GENERATED_HEADER + body


def build_root_entity(overlay_slug: str, workspace_count: int) -> dict:
    return {
        "apiVersion": "backstage.io/v1alpha1",
        "kind": "Component",
        "metadata": {
            "name": ROOT_COMPONENT_NAME,
            "title": "RHDH Plugin Export Overlays",
            "description": (
                "Packaging and OCI publish layer for RHDH dynamic plugins. "
                f"Contains {workspace_count} overlay workspaces."
            ),
            "annotations": {
                "github.com/project-slug": overlay_slug,
            },
            "tags": ["overlay", "dynamic-plugin", "repository"],
            "links": [
                {
                    "url": f"https://github.com/{overlay_slug}",
                    "title": "GitHub repository",
                    "icon": "github",
                    "type": "source",
                },
                {
                    "url": export_workflow_url(overlay_slug),
                    "title": "Publish workflow",
                    "type": "ci",
                },
            ],
        },
        "spec": {
            "type": "repository",
            "lifecycle": "experimental",
            "owner": "rhdh-team",
            "system": "rhdh",
        },
    }


def build_workspace_entity(
    workspace: str,
    source: dict,
    plugin_paths: list[str],
    overlay_slug: str,
    plugin_refs: list[str] | None = None,
    package_refs: list[str] | None = None,
) -> dict:
    plugin_count = len(plugin_paths)
    package_word = "package" if plugin_count == 1 else "packages"
    ref = source.get("repo-ref") or "main"
    short_ref = ref[:7] if len(ref) >= 7 else ref
    entity: dict = {
        "apiVersion": "backstage.io/v1alpha1",
        "kind": "Component",
        "metadata": {
            "name": overlay_entity_name(workspace),
            "title": f"Overlay workspace {workspace}",
            "description": (
                f"Dynamic-plugin export overlay for workspace '{workspace}' "
                f"({plugin_count} {package_word}). "
                f"Upstream source pinned at {short_ref}."
            ),
            "annotations": {
                "github.com/project-slug": overlay_slug,
                ANNOTATION_OVERLAY_WORKSPACE: workspace,
            },
            "tags": ["overlay", "dynamic-plugin"],
            "links": [
                {
                    "url": overlay_tree_url(overlay_slug, workspace),
                    "title": "Overlay workspace",
                    "icon": "github",
                    "type": "source",
                },
                {
                    "url": source_tree_url(source, workspace),
                    "title": "Upstream source",
                    "icon": "github",
                    "type": "upstream",
                },
                {
                    "url": export_workflow_url(overlay_slug),
                    "title": "Latest export workflow",
                    "type": "ci",
                },
            ],
        },
        "spec": {
            "type": "rhdh-overlay-workspace",
            "lifecycle": "experimental",
            "owner": "rhdh-team",
            "system": "rhdh",
            "subcomponentOf": f"component:default/{ROOT_COMPONENT_NAME}",
        },
    }
    source_repo = source.get("repo")
    if isinstance(source_repo, str) and source_repo:
        entity["metadata"]["annotations"][ANNOTATION_SOURCE_REPOSITORY] = (
            source_repo.rstrip("/")
        )
    source_revision = source.get("repo-ref")
    if isinstance(source_revision, str) and source_revision:
        entity["metadata"]["annotations"][ANNOTATION_SOURCE_REVISION] = source_revision

    if plugin_refs:
        entity["metadata"]["annotations"][ANNOTATION_PLUGIN_REFS] = ", ".join(
            plugin_refs
        )
    if package_refs:
        entity["metadata"]["annotations"][ANNOTATION_PACKAGE_REFS] = ", ".join(
            package_refs
        )

    depends_on = rhdh_plugins_depends_on(workspace)
    if depends_on and is_rhdh_plugins_source(source.get("repo", "")):
        entity["spec"]["dependsOn"] = [f"component:default/{depends_on}"]
    return entity


def discover_workspaces(repo_root: Path) -> list[Path]:
    workspaces_dir = repo_root / "workspaces"
    if not workspaces_dir.is_dir():
        return []
    found = []
    for path in sorted(workspaces_dir.iterdir()):
        if path.is_dir() and (path / "source.json").is_file():
            found.append(path)
    return found


def planned_files(
    repo_root: Path, overlay_slug: str
) -> list[tuple[Path, str]]:
    workspaces = discover_workspaces(repo_root)
    files: list[tuple[Path, str]] = [
        (
            repo_root / "catalog-info.yaml",
            dump_entity(build_root_entity(overlay_slug, len(workspaces))),
        )
    ]
    for workspace_dir in workspaces:
        source = load_source_json(workspace_dir)
        plugin_paths = read_plugins_list(workspace_dir)
        plugin_refs, package_refs = extension_refs(repo_root, workspace_dir)
        entity = build_workspace_entity(
            workspace_dir.name,
            source,
            plugin_paths,
            overlay_slug,
            plugin_refs,
            package_refs,
        )
        files.append((workspace_dir / "catalog-info.yaml", dump_entity(entity)))
    return files


def generated_catalog_paths(repo_root: Path) -> set[Path]:
    return {
        path
        for path in (
            repo_root / "catalog-info.yaml",
            *(repo_root / "workspaces").glob("*/catalog-info.yaml"),
        )
        if path.is_file()
    }


def is_generated_catalog_file(path: Path) -> bool:
    try:
        first_lines = "\n".join(path.read_text(encoding="utf-8").splitlines()[:2])
    except OSError:
        return False
    return first_lines == GENERATED_HEADER.rstrip()


def write_files(
    files: list[tuple[Path, str]], dry_run: bool, repo_root: Path | None = None
) -> None:
    for path, content in files:
        if dry_run:
            log_info(f"would write {path}")
            continue
        path.write_text(content, encoding="utf-8")
        log_info(f"wrote {path}")
    if dry_run or repo_root is None:
        return
    expected = {path for path, _ in files}
    for path in generated_catalog_paths(repo_root) - expected:
        if is_generated_catalog_file(path):
            path.unlink()
            log_info(f"removed obsolete generated file {path}")


def check_files(files: list[tuple[Path, str]]) -> int:
    stale = []
    for path, content in files:
        if not path.is_file():
            stale.append(f"missing {path}")
            continue
        if path.read_text(encoding="utf-8") != content:
            stale.append(f"stale {path}")
    if files:
        repo_root = files[0][0].parent
        expected = {path for path, _ in files}
        for path in generated_catalog_paths(repo_root) - expected:
            if is_generated_catalog_file(path):
                stale.append(f"unexpected generated file {path}")
    if stale:
        for item in stale:
            log_error(item)
        log_error(
            f"{len(stale)} catalog-info.yaml file(s) out of date. "
            "Re-run: python3 scripts/generateCatalogInfo.py"
        )
        return 1
    log_info(f"{len(files)} catalog-info.yaml file(s) up to date")
    return 0


def repo_root_from_script() -> Path:
    return Path(__file__).resolve().parent.parent


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Generate software-catalog catalog-info.yaml files for overlay "
            "workspaces."
        )
    )
    parser.add_argument(
        "--repo-root",
        type=Path,
        default=None,
        help="Overlay repository root (default: parent of scripts/)",
    )
    parser.add_argument(
        "--overlay-slug",
        default=DEFAULT_OVERLAY_SLUG,
        help=f"GitHub org/repo for this overlay fork (default: {DEFAULT_OVERLAY_SLUG})",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit 1 if generated files would change (do not write)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print paths that would be written, do not write",
    )
    parser.add_argument("--debug", action="store_true")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    set_debug(args.debug)
    repo_root = (args.repo_root or repo_root_from_script()).resolve()
    if not (repo_root / "workspaces").is_dir():
        log_error(f"no workspaces/ directory under {repo_root}")
        return 1

    files = planned_files(repo_root, args.overlay_slug)
    if not files:
        log_warn("no overlay workspaces with source.json found")
        return 1

    if args.check:
        return check_files(files)

    write_files(files, dry_run=args.dry_run)
    log_info(f"{len(files)} catalog-info.yaml file(s)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
