name: Publish RHDH Release Dynamic Plugin Images
on:
  push:
    branches:
      - 'release-**'
      - 'main'

jobs:
  export:
    uses: ./.github/workflows/publish-release-branch-workspace-plugins.yaml
    permissions:
      contents: write
      attestations: write
      packages: write
      id-token: write
